apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: poc

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - auth.yaml
  - user.yaml
  - post.yaml
  - notification.yaml
  - gateway.yaml
  - ingress.yaml
  - prometheus.yaml